# Python Insights - Analisando Dados com Python

### Case - Cancelamento de Clientes

Você foi contratado por uma empresa com mais de 800 mil clientes para um projeto de Dados. Recentemente a empresa percebeu que da sua base total de clientes, a maioria são clientes inativos, ou seja, que já cancelaram o serviço.

Precisando melhorar seus resultados ela quer conseguir entender os principais motivos desses cancelamentos e quais as ações mais eficientes para reduzir esse número.

Base de dados e arquivos: https://drive.google.com/drive/folders/1uDesZePdkhiraJmiyeZ-w5tfc8XsNYFZ?usp=drive_link

In [ ]:
# Passo a passo do projeto
#tabula converte de pdf para tabela
# Passo 01: Abri a base de dados (importar a base de dados)
# pip install pandas openpxl ipykernel nbformat plotly
import pandas as pd #para escrever menos, apelido para qualquer pacote
import plotly.express as px #Adicione essa linha antes de usar px.histogram
#!pip install plotly # Plotly Express (importado como px) é um módulo
# da biblioteca Plotly para Python, feito para
# criar gráficos interativos de forma rápida e com poucas linhas de código.
tabela  = pandas.read_csv("cancelamentos.csv")
display(tabela)

#dataframe pandas - tabela bandas

# Passo 02: Vizualizar a base de dados (identificar se tem as informações)
    # entender as informações disponíveis
    # possíveis problemas/erros na base de dados
    #informações que não te ajudam te atrapalham
    #KAGGLE BASE DE DADOS QUE AS EMPERSAS DISPONIBILIZAM PRA PESSOAS TREINAREM
    # INFORMAÇÕES VAZIAS

    #como tirar a coluna
    #lista de colunas > em colchetes lista_nome = ["Lira" ,"Talia","José"]
    #forma rápida, corrigir caracter 
tabela = tabela.drop(columns="CustomerID")
display(tabela)

Requirement already satisfied: plotly in C:\Users\Pica das galáxias\AppData\Local\Programs\Python\Python314\Lib\site-packages (6.6.0)
Requirement already satisfied: narwhals>=1.15.1 in C:\Users\Pica das galáxias\AppData\Local\Programs\Python\Python314\Lib\site-packages (from plotly) (2.18.1)
Requirement already satisfied: packaging in C:\Users\Pica das galáxias\AppData\Local\Programs\Python\Python314\Lib\site-packages (from plotly) (25.0)

,CustomerID,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,349936.0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,100634.0,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,301263.0,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,119358.0,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,130955.0,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...
49995,195680.0,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,43477.0,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,169273.0,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,310693.0,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,251915.0,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

,idade,sexo,tempo_como_cliente,frequencia_uso,ligacoes_callcenter,dias_atraso,assinatura,duracao_contrato,total_gasto,meses_ultima_interacao,cancelou
0,23.0,Male,13.0,22.0,2.0,1.0,Standard,Annual,909.58,23.0,0.0
1,49.0,Male,55.0,16.0,3.0,6.0,Premium,Monthly,207.00,29.0,1.0
2,30.0,Male,7.0,1.0,0.0,8.0,Basic,Annual,768.78,7.0,0.0
3,26.0,Male,40.0,5.0,3.0,8.0,Premium,Annual,398.00,12.0,1.0
4,27.0,Female,17.0,30.0,5.0,6.0,Basic,Annual,507.00,15.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...
49995,62.0,Female,35.0,7.0,2.0,8.0,Basic,Annual,232.00,15.0,1.0
49996,36.0,Male,43.0,21.0,2.0,30.0,Basic,Quarterly,928.00,30.0,1.0
49997,55.0,Male,42.0,8.0,1.0,12.0,Basic,Monthly,326.00,27.0,1.0
49998,40.0,Female,14.0,19.0,1.0,17.0,Premium,Quarterly,826.76,12.0,0.0
49999,64.0,Male,41.0,29.0,5.0,9.0,Basic,Quarterly,700.38,18.0,1.0

In [ ]:
 
# Passo 03: corrigir os problemas da base de dados ( tratamento da base de dados) (adicionar anonimização)
display(tabela.info())

#nformações vazias
tabela = tabela.dropna() #NaN not a number = vazio = valores vazios
#para excluir valores duplicados drop_duplicates()
 
# Passo 03: corrigir os problemas da base de dados ( tratamento da base de dados) (adicionar anonimização)
display(tabela.info())

# COMO IDENTIFICO? Como analiso ?
#Pode tratar a informação, modificando ela de alguma maneira inteligente ou excluindo ela.
#identificar os problema

<class 'pandas.core.frame.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  object
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  object
 7   duracao_contrato        49996 non-null  object
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.6+ MB

None

<class 'pandas.core.frame.DataFrame'>
Index: 49996 entries, 0 to 49999
Data columns (total 11 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   idade                   49996 non-null  float64
 1   sexo                    49996 non-null  object
 2   tempo_como_cliente      49996 non-null  float64
 3   frequencia_uso          49996 non-null  float64
 4   ligacoes_callcenter     49996 non-null  float64
 5   dias_atraso             49996 non-null  float64
 6   assinatura              49996 non-null  object
 7   duracao_contrato        49996 non-null  object
 8   total_gasto             49996 non-null  float64
 9   meses_ultima_interacao  49996 non-null  float64
 10  cancelou                49996 non-null  float64
dtypes: float64(8), object(3)
memory usage: 4.6+ MB

None

In [ ]:
# Passo 04: Análise inicial (entender quantos clientes cancelaram)

#quantidade - contar quantos caras são 0 e quantos são 1 na coluna cancelou
display(tabela["cancelou"].value_counts())
#min média

#porcentagem
display(tabela["cancelou"].value_counts(normalize=True)) #se eu rodar vai dizer o percentual deles


#display(tabela["cancelou"].value_counts(normalize=True).map("{:.1%}".format)) #código de formatação

cancelou
1.0    28393
0.0    21603
Name: count, dtype: int64

cancelou
1.0    0.567905
0.0    0.432095
Name: proportion, dtype: float64

cancelou
1.0    56.8%
0.0    43.2%
Name: proportion, dtype: object

In [33]:
# Passo 05: análise detalhada para entender a causa do cancelamento, como cada coluna impacta no cancelamento
# primeiro cria o gráfico
grafico = px.histogram(tabela, x="cancelou")
# eixo y quantidade de pessoas, x = pessoas que cancelaram

#exibe o gráfico

grafico.show()